# -*- coding: utf-8 -*-
"""gnews_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSiY1KGnE2p78ATlo-8HJeJ97mtj02L8
"""

import json
import urllib.request
import pandas as pd
import datetime

apikey = '2339c6438f29d3c8903f7b08c1fe3ec9'

def get_news(category = 'general', lang = 'en', country = 'us', length = 10, apikey=''):
  url = f"https://gnews.io/api/v4/top-headlines?category={category}&lang={lang}&country={country}&max={length}&apikey={apikey}"
  response = urllib.request.urlopen(url)
  data = json.loads(response.read().decode("utf-8"))
  articles = data["articles"]
  return articles

def to_dataframe(articles):
  df = pd.json_normalize(articles)
  df = df[['title', 'url', 'publishedAt', 'source.name']]
  df.rename(columns = {'source.name': 'source'}, inplace = True)
  df['publishedAt'] =  pd.to_datetime(df['publishedAt'] , infer_datetime_format=True)
  return df

def save_articles(df):
  year = datetime.date.today().year     
  month = datetime.date.today().month    
  day = datetime.date.today().day      
  hour = datetime.datetime.now().hour 
  df.to_parquet(f"gnews_articles_{year}_{month}_{day}_{hour}.parquet")   


articles = get_news(apikey=apikey)
df = to_dataframe(articles)
save_articles(df)